from __future__ import annotations

from uuid import UUID, uuid4

from pydantic import BaseModel, ConfigDict, Field

from app.schemas.retrieval import RetrievalResult


class Citation(BaseModel):
    """
    Represents a citation supporting the generated answer.
    """

    model_config = ConfigDict(extra="forbid")

    source_title: str = Field(
        ...,
        description="Title of the source document.",
    )

    page_number: int | None = Field(
        default=None,
        ge=1,
        description="Page number within the source document.",
    )

    section: str | None = Field(
        default=None,
        description="Section within the source document.",
    )


class QueryRequest(BaseModel):
    """
    Request received by the API.
    """

    model_config = ConfigDict(extra="forbid")

    question: str = Field(
        ...,
        min_length=1,
        description="Medical question asked by the user.",
    )

    top_k: int = Field(
        default=5,
        ge=1,
        le=20,
        description="Maximum number of chunks to retrieve.",
    )

    include_sources: bool = Field(
        default=True,
        description="Whether supporting citations should be returned.",
    )


class MedicalAnswer(BaseModel):
    """
    Grounded answer generated by the LLM.
    """

    model_config = ConfigDict(extra="forbid")

    answer: str = Field(
        ...,
        min_length=1,
        description="Generated answer.",
    )

    citations: list[Citation] = Field(
        default_factory=list,
        description="Supporting citations.",
    )

    grounded: bool = Field(
        default=True,
        description="Whether the answer is grounded in retrieved documents.",
    )


class QueryResponse(BaseModel):
    """
    Response returned by the API.
    """

    model_config = ConfigDict(extra="forbid")

    query_id: UUID = Field(
        default_factory=uuid4,
        description="Unique query identifier.",
    )

    question: str = Field(
        ...,
        description="Original user question.",
    )

    answer: MedicalAnswer = Field(
        ...,
        description="Generated medical answer.",
    )

    retrieval_result: RetrievalResult = Field(
        ...,
        description="Retrieval details.",
    )

    latency_ms: float = Field(
        default=0.0,
        ge=0.0,
        description="End-to-end response latency in milliseconds.",
    )